"use client";

import { Header } from "@/components/layout/Header";
import { Footer } from "@/components/layout/Footer";
import { Container } from "@/components/layout/Container";

export default function TermsPage() {
    return (
        <div className="flex min-h-screen flex-col bg-[#0f172a]">
            <Header />
            <main className="flex-1 py-32">
                <Container>
                    <div className="max-w-3xl mx-auto glass-card p-8 md:p-12">
                        <h1 className="text-3xl font-bold text-white mb-8">Terms of Service</h1>

                        <div className="prose prose-invert prose-lg text-slate-400">
                            <p className="lead text-xl text-slate-300">
                                Please Read Carefully: This is a Portfolio Project.
                            </p>

                            <h3 className="text-white mt-8 mb-4">1. Nature of this Application</h3>
                            <p>
                                The "Negotiate Contracts" application is a <strong>portfolio project</strong> created by
                                <a href="http://anthonymax.com/" target="_blank" rel="noopener noreferrer" className="text-blue-400 hover:text-blue-300 mx-1">
                                    Anthony Max
                                </a>
                                to demonstrate technical capabilities in AI Product Building, Full-stack Development, and User Interface Design.
                            </p>

                            <h3 className="text-white mt-8 mb-4">2. No Legal Advice</h3>
                            <p>
                                <strong>This application does not provide legal advice.</strong> The analysis, risk scores, and rewrite suggestions
                                generated by the Artificial Intelligence are for demonstration purposes only. They should never be used as a
                                substitute for professional legal counsel.
                            </p>

                            <h3 className="text-white mt-8 mb-4">3. Use at Your Own Risk</h3>
                            <p>
                                By using this application, you acknowledge that:
                            </p>
                            <ul className="list-disc pl-5 space-y-2">
                                <li>The results may contain errors or inaccuracies.</li>
                                <li>You should not make financial or legal decisions based solely on this tool.</li>
                                <li>The creator accepts no liability for any reliance placed on this demonstration.</li>
                            </ul>

                            <h3 className="text-white mt-8 mb-4">4. Intellectual Property</h3>
                            <p>
                                The code, design, and implementation of this project are the intellectual property of Anthony Max.
                                This project allows potential clients and employers to evaluate technical skills.
                            </p>

                            <div className="mt-12 pt-8 border-t border-slate-700">
                                <p className="text-sm">
                                    Last updated: December 2025
                                </p>
                            </div>
                        </div>
                    </div>
                </Container>
            </main>
            <Footer />
        </div>
    );
}
